name: QuizWhiz
title: QuizWhiz - Interactive Quiz Platform
description: A dynamic quiz application built with PHP and MySQL
baseurl: "/QuizWhiz"
url: "https://ashwinshetty3.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
- jekyll-feed
- jekyll-seo-tag

# Exclude files from processing
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
